version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo Installing dependencies
      - pip install -r requirements.txt
      - cd frontend
      - npm install
      - npm run build
  build:
    commands:
      - echo Build started
      - cd ..
      - cp -r frontend/build backend/static
  artifacts:
    files:
      - '**/*'